; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=HydraTouch
;\\\\\\\\\\\\\\\\\\\\\\
;AppVerName=HydraTouchLite Upper 1.9.6 (16/06/16)
;OutputDir=output\stdTouchLiteUpper-1.9.6
AppVerName=HydraTouchLite 4.0.0 (18/01/26) I.M. TICF,RCC,DCF,TCF. TT AFG
OutputDir=output\TouchLite-STD-4.0.0
;//////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\HydraTouch
DefaultGroupName=Hydra
AlwaysShowComponentsList=true
PrivilegesRequired=admin
DisableDirPage=no
AlwaysShowDirOnReadyPage=yes

[Types]
Name: hydratouch;    Description: HydraTouch;     flags: iscustom;

[Components]
Name: MULTI;            Description: MultiStore Module;                         Flags: disablenouninstallwarning restart;       MinVersion: 4.0,4.0;
Name: DCOM95;           Description: DCOM for Windows 95;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0;        Types: hydratouch;
Name: DCOM98;           Description: DCOM for Windows 98;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.1,0;                                      Types: hydratouch;
Name: MDAC25;           Description: Microsoft Data Access Components 2.5;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0;      Types: hydratouch;
Name: MDAC27;           Description: Microsoft Data Access Components 2.7;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.9,5.0;                                    Types: hydratouch;

[Tasks]
Name: "desktopicon";            Description: "Crear Icono en el Escritorio";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked
Name: "quicklaunchicon";        Description: "Crear Icono de Acceso Rápido";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked

[Files]
;//////
; APP
;//////
; begin VB system files
; (Note: Scroll to the right to see the full lines!)
;Source: "c:\windows\system32\stdole2.tlb";  DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regtypelib
;Source: "vbfiles\msvbvm60.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\oleaut32.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\olepro32.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\asycfilt.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile
;Source: "vbfiles\comcat.dll";   DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
; end VB system files
Source: hydraTouch.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite
;Source: cop5.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite
;Agora
;Source: agora.txt;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
;Multi
Source: hydramulti.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite;  Components: MULTI; 
;;;;;;
Source: tiqahTouch.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: convertimg.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite;  
;Covalco
;Source: cuenca\*.*;             destdir: "{app}"; copymode: alwaysoverwrite
;;;;;;;;
Source: zip.exe;                DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: unzip.exe;              DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: mizip.exe;              DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: vacio.jpg;              DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: backgrounde.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: hydra-background-1024x768_1.jpg; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: f1.jpg;                 DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: auxiliartouch.exe;      DestDir: "{app}"; CopyMode: alwaysoverwrite;  
;Source: cmdline.cfg;         DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: copiontouch.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: sobrebase;        DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: "registratouch\registratouch.bat";   DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: "registratouch\registratouch.exe";   DestDir: "{app}"; CopyMode: alwaysoverwrite;
;//UPPER
;Source: upper.txt;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
;Source: nolabel.txt;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
;Source: upperjpg.txt;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
;//////
Source: ctrlimpatouch.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
Source: sidebar.ocx;           DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
;Source: adaptafam;           DestDir: "{app}"; CopyMode: alwaysoverwrite
;//////
Source: langtouch\langtouch.mdb;    DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\1.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\2.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\3.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\4.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\5.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\6.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\7.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\8.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\9.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\langtouch.mdb;    DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\1.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\2.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\3.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\4.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\5.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\6.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\7.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\8.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\9.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: etc\std\artcon.dat.fia;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: etc\std\bal.dat.fia;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: etc\std\*.fet;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: images\*.*;     destdir: "{app}\images"; copymode: alwaysoverwrite

;//////
Source: C:\inno_appEPELSA\3rdparty\inno.txt;        DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\zip_unzip.txt;   DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\xcopy.zip;       DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
;//////

;//////
; SYS
;//////
Source: systray.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite;         Flags : sharedfile regserver
source: unrar.dll;                            destdir: "{app}"; CopyMode: alwaysoverwrite;
Source: c:\windows\system32\systray.ocx;     DestDir: "{sys}"; CopyMode: alwaysoverwrite;         Flags : sharedfile regserver
;onlyifdoesntexist
Source: c:\windows\system32\RICHTX32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\COMDLG32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRID32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCHRT20.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMCTL.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMM32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSMASK32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSWINSCK.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\TABCTL32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
;//////
Source: c:\windows\system32\RCHTXES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RICHED32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appepelsa\system\DAO350.DLL; DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\inno_appepelsa\system\DAO360.DLL; DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\ASYCFILT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appEPELSA\system\COMCAT.DLL; DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRDES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\DBRPRES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\expsrv.dll;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSBIND.DLL;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCH2ES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCMCES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCOMES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSDBRPTR.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\msderun.dll;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET35.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\msjtes40.dll;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET40.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSMSKES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSPRPES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSRD2X35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD2X40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD3X40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSREPL35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSREPL40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSSTDFMT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSSTKPRP.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSVBVM60.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSXBSE35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\odbcconf.dll;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEAUT32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEPRO32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\SCRRNES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\SCRRUN.DLL;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\STDFTES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\TABCTES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB5DB.DLL;       DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6ES.DLL;       DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6STKIT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VBAJET32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\WINSKES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RDOCURS.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile 
Source: c:\windows\system32\RDO20ES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile 
Source: c:\windows\system32\STDOLE2.TLB;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSVCRT40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSRDO20.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver

; ///
; LIB
; ///
Source: C:\inno_appEPELSA\lib\dcom95.EXE;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,0;   Components: DCOM95;     OnlyBelowVersion: 4.1,0;
Source: C:\inno_appEPELSA\lib\dcom98.exe;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.1,0;   Components: DCOM98;
Source: C:\inno_appEPELSA\lib\mdac_typ_25.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,4.0; Components: MDAC25;      OnlyBelowVersion: 4.9,5.0;
Source: C:\inno_appEPELSA\lib\mdac_typ_27.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.9,5.0; Components: MDAC27;
Source: mysql-connector-odbc-5.1.11-win32.msi;    DestDir: "{app}"; CopyMode: alwaysoverwrite


[Icons]
;Agora
Name: "{userstartup}\TiqAhTouch"; Filename: "{app}\tiqahtouch.exe";
Name: "{commonstartup}\TiqAhTouch"; Filename: "{app}\tiqahtouch.exe";
;;;;;;

Name: "{group}\HydraTouch";                                                  Filename: "{app}\hydraTouch.exe"; WorkingDir: {app}
Name: "{userdesktop}\HydraTouch";                                            Filename: "{app}\hydraTouch.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\HydraTouch";   Filename: "{app}\hydraTouch.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: quicklaunchicon

[Dirs]
Name: {app}; Permissions: users-full
Name: "{app}\etc"; Permissions: users-full
Name: "{app}\lang"; Permissions: users-full
Name: "{app}\langtouch"; Permissions: users-full
Name: "{app}\dirtmp"; Permissions: users-full
Name: "{app}\images"; Permissions: users-full
Name: "{app}\exporta"; Permissions: users-full
Name: "{app}\backup"; Permissions: users-full
Name: "{app}\images"; Permissions: users-full
Name: "(app)\3rdparty"; Permissions: users-full
Name: "{app}\asorden"; Permissions: users-full

[Run]
Filename: {tmp}\dcom95.EXE;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM95;     MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0
Filename: {tmp}\dcom98.exe;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM98;     MinVersion: 4.1,0
Filename: {tmp}\mdac_typ_25.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC25;     MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0
Filename: {tmp}\mdac_typ_27.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC27;     MinVersion: 4.9,5.0;
;;;3.2.8 Filename: {app}\registratouch.exe;      WorkingDir: {app}; Flags: runascurrentuser
;Filename: "{app}\msiexec.exe /i mysql-connector-odbc-5.1.13-win32.msi /quiet"
;////////
Filename: "{app}\hydratouch.exe";            Description: "Launch Hydra";            Flags: nowait postinstall skipifsilent

;[Code]
;begin
;var
;  MyChk: String;
;  if IsWin64 then
;  begin
;    MyChk:='HKLM64';
;  end;
;  else 
;  begin
;    MyChk:='HKLM32';
;  end;
;end;

[Registry]
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;

Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;

;current user only
Root: HKCU32; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: not IsWin64
Root: HKCU64; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: IsWin64

;any user
Root: HKLM32; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: not IsWin64
Root: HKLM64; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: IsWin64

; keys for 32-bit systems
;Root: HKCU32; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: not IsWin64
;Root: HKLM32; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: not IsWin64

; keys for 64-bit systems
;Root: HKCU64; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: IsWin64
;Root: HKLM64; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: IsWin64

;REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\temp\compatmodel\iconsext.exe" /t REG_SZ /d "WINXPSP3 RUNASADMIN" /f
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\hydratouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\hydramulti.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
;Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\auxiliartouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\copiontouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\zip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\unzip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\mizip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;

Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\hydratouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\hydramulti.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
;Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\auxiliartouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\copiontouch.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\zip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\unzip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\mizip.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;
 
root: HKCU; Subkey: "Software\GrupoEpelsa"; Flags: uninsdeletekeyifempty
root: HKCU; Subkey: "Software\Grupoepelsa\hydratouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa"; Flags: uninsdeletekeyifempty
root: HKLM; Subkey: "Software\GrupoEpelsa\hydratouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\hydratouch.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\hydramulti.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\hydramulti.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\hydramulti.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

;root: HKCU; Subkey: "Software\Grupoepelsa\tiqahtouch.exe"; Flags: uninsdeletekey
;root: HKLM; Subkey: "Software\GrupoEpelsa\tiqahtouch.exe"; Flags: uninsdeletekey
;root: HKLM; Subkey: "Software\GrupoEpelsa\tiqahtouch.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\auxiliartouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\auxiliartouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\auxiliartouch.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\copiontouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\copiontouch.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\copiontouch.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\zip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\zip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\zip.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\unzip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\unzip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\unzip.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

root: HKCU; Subkey: "Software\Grupoepelsa\mizip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\mizip.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\mizip.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full
;;;;;
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;

Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;

Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Flags: uninsdeletevalue;

;current user only
Root: HKCU32; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: not IsWin64
Root: HKCU64; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: IsWin64

;any user
Root: HKLM32; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: not IsWin64
Root: HKLM64; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "tiqahtouch"; ValueData: """{app}\tiqahtouch.exe"""; Check: IsWin64

; keys for 32-bit systems
;Root: HKCU32; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: not IsWin64
;Root: HKLM32; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: not IsWin64

; keys for 64-bit systems
;Root: HKCU64; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: IsWin64
;Root: HKLM64; \
    Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\tiqahtouch.exe"; ValueData: "RUNASADMIN"; \
    Flags: uninsdeletekeyifempty uninsdeletevalue; Check: IsWin64