; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Hydra+
;\\\\\\\\\\\\\\\\\\\\\\\\\\\\
AppVerName=HydraTouch 3.3.5 patch MT-Rio
OutputDir=output\mettler\parche
;////////////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\Hydra
DefaultGroupName=Hydra
AlwaysShowComponentsList=true
AdminPrivilegesRequired=true


[Types]
Name: hydra; Description: Hydra; flags: iscustom;


[Tasks]
Name: "desktopicon";            Description: "Crear Icono en el Escritorio"; GroupDescription: "Additional icons:"; MinVersion: 4,4;    Flags: unchecked
Name: "quicklaunchicon";        Description: "Crear Icono de Acceso Rápido"; GroupDescription: "Additional icons:"; MinVersion: 4,4;    Flags: unchecked


[Files]
;//////
;   APP
;//////
Source: C:\inno_appEPELSA\3rdparty\inno.txt;        DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\zip_unzip.txt;   DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\xcopy.zip;       DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\mettler\in.txt.fia;       DestDir: "{app}\etc";           CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\mettler\touch\cmdlinetouch.cfg;      DestDir: "{app}";               CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\mettler\tiendamt.txt;     DestDir: "{app}";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\mettler\touch\tiqahtouch.ini;        DestDir: "{app}";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\mettler\tramos.dat.fia;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite

