"ÏÌÇÇÏÌÆÎ","NEVER EDIT NOR REMOVE THIS LINE"
0,"Language / Idioma"
"C:\Proyectos_VB6\hydra+TouchScale\backup","Backup Path / Ruta para copias de seguridad"
0,"Export : Date Format / Formato de Fecha"
0,"Export : Time Format / Formato de Hora"
"0","Export : positive symbol / Signo Positivo"
"1","Export : negative symbol / Signo Negativo"
#FALSE#,"Export : Use Absolute Values / Usar valores Absolutos"
#FALSE#,"Export : Only Data from current Date / Sólo datos del día en curso"
