; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=Alimerka
;\\\\\\\\\\\\\\\\\\\\\\
AppVerName=Alimerka 1.12
OutputDir=output
;//////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName=c:\GPELSA
DefaultGroupName=Alimerka
AlwaysShowComponentsList=true
PrivilegesRequired=admin
DisableDirPage=no
AlwaysShowDirOnReadyPage=yes

[Types]
Name: Alimerka;    Description: Alimerka;     flags: iscustom;

[Components]
Name: DCOM95;           Description: DCOM for Windows 95;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0;        Types: Alimerka;
Name: DCOM98;           Description: DCOM for Windows 98;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.1,0;                                      Types: Alimerka;
Name: MDAC25;           Description: Microsoft Data Access Components 2.5;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0;      Types: Alimerka;                                    
Name: MDAC27;           Description: Microsoft Data Access Components 2.7;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.9,5.0;                                    Types: Alimerka;

[Tasks]
Name: "desktopicon";            Description: "Crear Icono en el Escritorio";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked
Name: "quicklaunchicon";        Description: "Crear Icono de Acceso Rápido";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked

[Files]
;//////
; APP
;//////
Source: Alimerka.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite
;Source: serip.txt;            DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: servidoras.txt;            DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: paths.txt;            DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: mysql-connector-odbc-5.1.11-win32.msi; DestDir: "{app}"; CopyMode: alwaysoverwrite

;//////
Source: C:\inno_appEPELSA\3rdparty\inno.txt;        DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: systray.txt;        DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
;//////
; SYS
;//////
;onlyifdoesntexist
Source: c:\windows\system32\RICHTX32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\COMDLG32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRID32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCHRT20.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMCTL.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMM32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSMASK32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSWINSCK.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\TABCTL32.OCX;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
;//////
Source: c:\windows\system32\RCHTXES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RICHED32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appepelsa\system\DAO350.DLL;                 DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\hydra+Touchscale\Paquete\Support\DAO360.DLL;      DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\ASYCFILT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appEPELSA\system\COMCAT.DLL; DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRDES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\DBRPRES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\expsrv.dll;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSBIND.DLL;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCH2ES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCMCES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCOMES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSDBRPTR.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\msderun.dll;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET35.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\msjtes40.dll;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET40.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSMSKES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSPRPES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSRD2X35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD2X40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD3X40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSREPL35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSREPL40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSSTDFMT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSSTKPRP.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSVBVM60.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSXBSE35.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\odbcconf.dll;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEAUT32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEPRO32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\SCRRNES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\SCRRUN.DLL;      DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\STDFTES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\TABCTES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB5DB.DLL;       DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6ES.DLL;       DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6STKIT.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VBAJET32.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\WINSKES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RDOCURS.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile 
Source: c:\windows\system32\RDO20ES.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile 
Source: c:\windows\system32\STDOLE2.TLB;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSVCRT40.DLL;    DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSRDO20.DLL;     DestDir: "{sys}"; Flags: onlyifdoesntexist allowunsafefiles restartreplace uninsneveruninstall sharedfile regserver

; ///
; LIB
; ///
Source: C:\inno_appEPELSA\lib\dcom95.EXE;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,0;   Components: DCOM95;     OnlyBelowVersion: 4.1,0;
Source: C:\inno_appEPELSA\lib\dcom98.exe;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.1,0;   Components: DCOM98;
Source: C:\inno_appEPELSA\lib\mdac_typ_25.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,4.0; Components: MDAC25;      OnlyBelowVersion: 4.9,5.0;
Source: C:\inno_appEPELSA\lib\mdac_typ_27.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.9,5.0; Components: MDAC27;

[Icons]
Name: "{group}\Alimerka";                                                    Filename: "{app}\Alimerka.exe"; WorkingDir: {app}
Name: "{userdesktop}\Alimerka";                                            Filename: "{app}\Alimerka.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Alimerka";   Filename: "{app}\Alimerka.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: quicklaunchicon

[Dirs]
Name: {app}; Permissions: users-full
Name: "{app}\procesados"; Permissions: users-full
Name: "C:\tiquetbal"; Permissions: users-full

[Run]
Filename: {tmp}\dcom95.EXE;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM95;     MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0
Filename: {tmp}\dcom98.exe;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM98;     MinVersion: 4.1,0
Filename: {tmp}\mdac_typ_25.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC25;     MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0
Filename: {tmp}\mdac_typ_27.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC27;     MinVersion: 4.9,5.0;

[Registry]
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\Alimerka.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;

Root: "HKCU"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\"; ValueType: String; ValueName: "{app}\Alimerka.exe"; ValueData: "~ WINXPSP3 RUNASADMIN"; Flags: uninsdeletekeyifempty uninsdeletevalue;

root: HKCU; Subkey: "Software\GrupoEpelsa"; Flags: uninsdeletekeyifempty
root: HKCU; Subkey: "Software\Grupoepelsa\Alimerka.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa"; Flags: uninsdeletekeyifempty
root: HKLM; Subkey: "Software\GrupoEpelsa\Alimerka.exe"; Flags: uninsdeletekey
root: HKLM; Subkey: "Software\GrupoEpelsa\Alimerka.exe\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Permissions: users-full

