"ÌÇÉÏÌÇÉÌ","NEVER EDIT NOR REMOVE THIS LINE"
0,"Idioma "
"","Nombre de la Empresa"
1,"Utilizar ScalePos"
0,"Utilizar Concentrador SC-10"
0,"Utilizar Fichas de Vacuno"
0,"Utilizar Grupos de Conservacion"
0,"Utilizar Gedit"
#FALSE#,"Ethernet(#TRUE#) o RS-232(#FALSE#)"
"19200,E,8,1,1","Parametros del Puerto Serie RS-232 ScalePos"
"6000","Puerto TCP/IP"
"z:\sc10","Ruta de Red del Concentrador SC-10"
0,"Recepción contínua de Tiquets"
"","Intervalo de Recepción de Tiquets"
1,"ScalePos:Recibir Totales Venta"
0,"ScalePos:Recibir Totales Super"
0,"ScalePos:Recibir Totales Envasado"
0,"ScalePos:Recibir Totales Autoservicio"
1,"ScalePos:Recibir Totales Venta Local"
0,"ScalePos:Recibir Totales Super Local"
0,"ScalePos:Recibir Totales Envasado Local"
0,"ScalePos:Recibir Totales Autoservicio Local"
1,"ScalePos:Borrar Totales"
0,"SC10:Borrar Totales"
1,"SC10:Recibir Totales Venta"
0,"SC10:Recibir Totales Super"
0,"SC10:Recibir Totales Envasado"
0,"SC10:Recibir Totales Autoservicio"
0,"SC10:Borrar Ticket.dat"
0,"SC10:Borrar Eti.dat"
0,"Recibir Totales de Fichas de Vacuno"
0,"Borrar Totales de Fichas de Vacuno"
"0","Decimales de la Moneda"
"Pta.","Símbolo de Moneda Nacional"
0,"Reservado"
"Euro","Moneda a Utilizar (Nacional/Euro)"
0,"Realizar Backup de la Base"
"","Ruta de Backup"
"37","Familia Especial"
"7","Etiqueta Especial"
"","Ubicación de DBTECLAS.DBF"
"0","Nro. de Decimales moneda nacional"
"Pta.","Símbolo de la moneda Nacional"
1,"Usar 20 líneas de Descriptivo"
"0","Reservado"
#FALSE#,"Comunicación Rs232 con SC10"
"19200,E,8,1,2","Parametros del Puerto Serie RS-232 SC10"
#TRUE#,"Reservado"
25,"Hora de Cierre"
61,"Minuto de Cierre"
25,"Hora de Recogida"
61,"Minuto de Recogida"
"127.000.000.001","Host - Enlace Socket"
"5580","Puerto TCP - Enlace Socket"
"6001","Puerto UDP - Enlace Socket"
0,"Enlace Socket"
0,"Enlace ASCII"
"balglo.dat","Enlace ASCII - fichero de importación contínua"
"1","Enlace ASCII - Dejar ficheros de tiquets"
0,"Iconificar en barra de estado"
0,"Iconificar al inicio"
0,"Log de Artículos"
0,"Log del Sistema"
"","Comando Libre - Nombre"
"","Comando Libre - Linea de comandos"
"","Comando Libre - Nombre"
"","Comando Libre - Linea de comandos"
"","Comando Libre - Nombre"
"","Comando Libre - Linea de comandos"
"","Comando Libre - Nombre"
"","Comando Libre - Linea de comandos"
"","Comando Libre - Nombre"
"","Comando Libre - Linea de comandos"
0,"Activar Pantallas Remotas"
"32337","Puerto de Pantallas Remotas"
#FALSE#,"Utilizar Moneda distinta del Euro"
"","Borrar totales más antiguos de ... días"
"","Borrar copias de seguridad más antíguas de ... días"
0,"Exportación - Formato de Fecha"
0,"Exportación - Formato de Hora"
"0","Exportación - Signo positivo"
"1","Exportación - Signo negativo"
0,"Exportación - Utilizar valores absolutos"
"C:\1","Exportación - Path"
#FALSE#,"Exportación - Sólo Diario"
"BBTTTT","Nombre Fichero Tiquets"
"0","ASCII : envío directo"
"0","Vacuno versión D o posterior"
"0","Ticket ASCII en fichero único"
"","Nombre Fichero Tiquets Único"
1,"Reiniciar Numeración de Tiquets ScalePos"
#FALSE#,"Concentrador C9 o C10"
0,"Número de Secciones C9 o C10"
0,"Chequeo Rígido de Tiquets"
0,"Versión D : clientes"
1,"Modem --> Puerto"
1,"Modem --> Velocidad"
"","Modem --> Teléfono"
"","Modem --> Cadena"
"","Modem --> Cadena"
"","Modem --> Cadena"
1,"Modem --> Colgar Automáticamente"
0,"Modem --> Sí(1) o No(2)"
0,"Usa Pasarela Remota"
"127.000.000.001","Host Pasarela"
"32340","Puerto Pasarela"
0,"Absorver Cambios de Precio de Balanzas"
0,"Rechazar artículos con Precio cero"
"0","Solicitar pedido en recogida contínua"
"0","borrar pedido tras cada recogida"
"1","Borrar pedido a fin de día"
"0","Solicitar inventario en recogida contínua"
"0","borrar inventario tras cada recogida"
"1","borrar inventario a fin de día"
"0","Solicitar pedido a fin de día"
"0","solicitar inventario a fin de día"
0,"Equipos EcoNet / V8"
#TRUE#,"Tipo EcoNet (true) o V8 (false)"
0,"Equipos Marte IC-ILC"
"0","Número equipo V8/Marte IC-ILC conectado"
"0","Número equipo Marte IC-ILC conectado"
-1,"puerto RS-232 Marte IC-ILC/V8"
-1,"puerto RS-232 Marte IC-ILC"
0,"Equipos IV4 LCD / IV4"
0,"Tipo IV4"
-1,"puerto RS-232 Marte IC-ILC"
0,"Estilo de la interfaz"
0,"Marte/IV4 - Comunicar sólo con una máquina"
0,"IV4 TQ - Solicitar pedido/inventario al recibir totales"
0,"Envío contínuo + Recoger tiquets contínuo"
0,"Trabajo con múltiples servidoras ScalePos"
0,"SC10 - 4 líneas de descriptivo"
1,"Familias fijas"
3,"Reintentos de comunicación"
0,"Subsecciones fijas"
#FALSE#,"Comunicación TCP/IP con SC10"
"127.0.0.1","IP SC10"
"0","Port SC10"
0,"C10 / C9 COD"
0,"version G: Lineas 20 - 40"
0,"Comunicación Marte 9600"
0,"Comunicación Marte 19200"
0,"Marte Nuevo Protocolo"
0,"Marte Alfanumérica"
0,"Marte Alfanumérica 49T"
0,"Marte Alfanumérica 66T"
0,"Versión 00L-??? o posterior"
