; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=DLL/OCX Comunicaciones Sistemas Grupo Epelsa
AppVerName=DLL Versión 3.1.45, OCX Versión 3.1.45
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\EPDLLOCX

[Types]
Name: DLL ; Description: Utilidad Comunicación;


[Files]
; /////////////////////////////
; Archivos de Programa
; /////////////////////////////
Source: "EpelDLL.dll"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "EpelOCX.ocx"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "epelcom_es.pdf"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "c9sec.cfg"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSVBVM60.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\OLEAUT32.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\OLEPRO32.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\ASYCFILT.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\STDOLE2.TLB";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\COMCAT.DLL";   DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\VB6STKIT.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\VB6ES.DLL";    DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSWINSCK.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\WINSKES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSCOMM32.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSCOMES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSSTKPRP.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSPRPES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSCOMCTL.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSCMCES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSVCRT40.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\RDO20ES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\RDOCURS.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\MSRDO20.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\VB5DB.DLL";    DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\MSREPL35.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSRD2X35.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\expsrv.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\vbajet32.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\msjint35.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSJTER35.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSJET35.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\DAO350.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver

