-- CREATE DATABASE IF NOT EXISTS pcscale;
-- GRANT ALL PRIVILEGES ON pcscale.* TO 'pcscale'@'%' IDENTIFIED BY 'epelsa';
-- USE pcscale;
CREATE TABLE IF NOT EXISTS Items         ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Code INTEGER UNIQUE, Name TEXT NOT NULL, ShortName VARCHAR(32) NOT NULL, Text TEXT, Family INTEGER, Price DECIMAL(6,2) DEFAULT 0, SaleForm SMALLINT DEFAULT 1, PLU INTEGER DEFAULT 0, Counter INTEGER DEFAULT 0, VAT SMALLINT DEFAULT 0, EAN13 TEXT, Expiring SMALLINT DEFAULT 0, BestBefore SMALLINT DEFAULT 0, Tare DECIMAL(5,3) DEFAULT 0, Label TEXT NOT NULL, Icon TEXT NOT NULL, QLevel VARCHAR(8) NOT NULL, UNIQUE INDEX(Code), INDEX(Name(19)));
CREATE TABLE IF NOT EXISTS Vendors       ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Code INTEGER UNIQUE, Name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Counters      ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Code INTEGER UNIQUE, Name TEXT NOT NULL, Description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Scales        ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, MAC VARCHAR(17) UNIQUE NOT NULL, IP VARCHAR(16) NOT NULL, Number INTEGER, Name TEXT NOT NULL, Type CHAR(1));
CREATE TABLE IF NOT EXISTS HTickets      ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, tckType SMALLINT, Status CHAR(1), Number INTEGER DEFAULT 0, Counter INTEGER DEFAULT 0, Scale INTEGER DEFAULT 0, Vendor INTEGER, DatTim DATETIME, ReloadFrom INTEGER DEFAULT 0, Customer INTEGER DEFAULT 0, tckDiscount DECIMAL(4,2) DEFAULT 0, UNIQUE INDEX (Vendor,Id) );
CREATE TABLE IF NOT EXISTS LTickets      ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, IdHTicket INTEGER, lineType SMALLINT, SaleForm SMALLINT, Item INTEGER, Weight DECIMAL(5,3), lineDiscount DECIMAL(4,2), Price DECIMAL(6,2));
CREATE TABLE IF NOT EXISTS PayTickets    ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, IdHTicket INTEGER, PayMethod INTEGER, Delivered DECIMAL(8,2) DEFAULT 0 );
CREATE TABLE IF NOT EXISTS PayMethods    ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(30) UNIQUE NOT NULL );
CREATE TABLE IF NOT EXISTS VendorKeys    ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Counter INTEGER, VendorKey INTEGER, Vendor INTEGER, UNIQUE INDEX(Counter, VendorKey));
CREATE TABLE IF NOT EXISTS PLUKeys       ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Section INTEGER, Board INTEGER, PLUKey INTEGER, Code INTEGER, UNIQUE INDEX(Section, Board, PLUKey));
CREATE TABLE IF NOT EXISTS Bovine        ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, EarTag TEXT NOT NULL, BirthLand SMALLINT, BirthDate DATE, BreedingLand SMALLINT, SlaughterLand SMALLINT, SlaughterReg TEXT, SlaughterDate DATE, ButcherLand SMALLINT, ButcherReg TEXT, Lot TEXT, UNIQUE INDEX(Eartag(10)));
CREATE TABLE IF NOT EXISTS BarcodeEAN13	 ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, NumberType CHAR(1), Number SMALLINT DEFAULT 0, NetworkSales CHAR(12) NOT NULL, NetworkMixed CHAR(12) NOT NULL, NetworkSuper CHAR(12) NOT NULL, NetworkSS CHAR(12) NOT NULL, NetworkPacket1 CHAR(12) NOT NULL, NetworkPacket2 CHAR(12) NOT NULL, LocalSales CHAR(12) NOT NULL, LocalMixed CHAR(12) NOT NULL, LocalSuper CHAR(12) NOT NULL, LocalSS CHAR(12) NOT NULL, LocalPacket1 CHAR(12) NOT NULL, LocalPacket2 CHAR(12) NOT NULL, LocalTotal CHAR(12) NOT NULL, UNIQUE INDEX(NumberType, Number)  );
CREATE TABLE IF NOT EXISTS Status	 ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Version SMALLINT DEFAULT 0, TicketNumberType SMALLINT DEFAULT 0, ResetTicketNumber BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS NumTickets    ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Identifier INTEGER UNIQUE, Number INTEGER);
CREATE TABLE IF NOT EXISTS EraseTickets	 ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, DatTim DATETIME);
CREATE TABLE IF NOT EXISTS Trademark     ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, CO_Name TEXT NOT NULL, Description TEXT NOT NULL, Business TEXT NOT NULL, Slogan TEXT NOT NULL, Headquarter TEXT NOT NULL, CO_WEB TEXT NOT NULL, Shop_Name TEXT NOT NULL, Address TEXT NOT NULL, City TEXT NOT NULL, Phone TEXT NOT NULL, TIN TEXT NOT NULL, Shop_WEB TEXT NOT NULL, Text1 TEXT NOT NULL, Text2 TEXT NOT NULL, Text3 TEXT NOT NULL, Text4 TEXT NOT NULL, Text5 TEXT NOT NULL, Text6 TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS QLevels       ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Code VARCHAR(8) UNIQUE NOT NULL, Icon TEXT NOT NULL, Description TEXT NOT NULL );

-- Local tables
CREATE TABLE IF NOT EXISTS LocalStatus	 ( Id INTEGER PRIMARY KEY AUTO_INCREMENT, Version SMALLINT DEFAULT 0, ItemsUpdated BOOLEAN DEFAULT FALSE, EraseTickets BOOLEAN DEFAULT FALSE, RemoveScale BOOLEAN DEFAULT FALSE );
CREATE TABLE IF NOT EXISTS LocalHTickets  	LIKE HTickets;
CREATE TABLE IF NOT EXISTS LocalLTickets  	LIKE LTickets;
CREATE TABLE IF NOT EXISTS LocalPayTickets	LIKE PayTickets;
CREATE TABLE IF NOT EXISTS LocalNumTickets  LIKE NumTickets;

-- Initialization: Barcode EAN13 table 
REPLACE INTO BarcodeEAN13	VALUES(1,'G',0, '2YTTTTTIIIII', '20VVViiiiiii', '10VVVIIIIIII', '2YTTTTTIIIII', '2CCCCCCIIIII', '2CCCCCCIIIII', '2YTTTTTIIIII', '20VVViiiiiii', '10VVVIIIIIII', '2YTTTTTIIIII', '2CCCCCCIIIII', '2CCCCCCIIIII',  '2CCCCCCIIIII');

-- Initialization: Status tables 
REPLACE INTO Status			VALUES(1,0,0,FALSE);
REPLACE INTO LocalStatus	VALUES(1,0,FALSE,FALSE,FALSE);
REPLACE INTO EraseTickets	VALUES(1,NOW());
REPLACE INTO Trademark		VALUES(1,'','','','','','','','','','','','','','','','','','');

