"ноомноой","NEVER EDIT NOR REMOVE THIS LINE"
0,"Language / Idioma"
"C:\hydra+TouchScale\multi\backup","Backup Path / Ruta para copias de seguridad"
0,"Export : Date Format / Formato de Fecha"
0,"Export : Time Format / Formato de Hora"
"0","Export : positive symbol / Signo Positivo"
"1","Export : negative symbol / Signo Negativo"
#FALSE#,"Export : Use Absolute Values / Usar valores Absolutos"
#FALSE#,"Export : Only Data from current Date / SСlo datos del dМa en curso"
