; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=HydraTouch
;\\\\\\\\\\\\\\\\\\\\\\
AppVerName=HydraTouchLite Parche BDP Artcon (16/08/16)
OutputDir=output\BDP-2.0.2\parche
;//////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\HydraTouch\bdp\parche
DefaultGroupName=Hydra
AlwaysShowComponentsList=true
;//AdminPrivilegesRequired=true

[Files]
;//////
; APP
;//////
Source: hydraTouch.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: tiqahTouch.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: vacio.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: backgrounde.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: hydra-background-1024x768.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: f1.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: auxiliartouch.exe;     DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: zip.exe;          DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: unzip.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: copiontouch.exe;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: C:\inno_appEPELSA\BDP\bal.dat.fia;       DestDir: "{app}\etc"; CopyMode: alwaysoverwrite;
Source: etc\artcon.dat.fia;       DestDir: "{app}\etc"; CopyMode: alwaysoverwrite;
Source: cmdlinetouch.cfg;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: C:\inno_appEPELSA\BDP\bdp.txt;           DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: bdpnot.txt;           DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: cmdlinetouch.cfg;           DestDir: "{app}"; CopyMode: alwaysoverwrite;
;//////
Source: ctrlimpatouch.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
;Source: epelocx.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
;//////
;Source: langtouch\langtouch.mdb;    DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\1.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\2.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\3.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\4.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\5.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\6.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\7.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\8.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\9.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
;Source: langtouch\langtouch.mdb;    DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\1.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\2.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\3.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\4.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\5.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\6.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\7.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\8.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
;Source: langtouch\9.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite

