; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=touchup
;\\\\\\\\\\\\\\\\\\\\\\
AppVerName=touchup
;//////////////////////
DefaultDirName="c:\balanzas"
DefaultGroupName=touchup
AlwaysShowComponentsList=true

[Files]
;//////
; APP
;//////
Source: Touchup.exe;                     DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: c:\windows\system32\msinet.ocx;  DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver

