; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=HydraTouch
;\\\\\\\\\\\\\\\\\\\\\\
AppVerName=HydraTouchLite HiperUsera 3.2.7 (03/04/17)
OutputDir=output\stdTouchLiteHiperUsera327-030417 
;//////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\HydraTouch
DefaultGroupName=Hydra
AlwaysShowComponentsList=true
;PrivilegesRequired=admin
DisableDirPage=no
AlwaysShowDirOnReadyPage=yes

[Types]
Name: hydratouch;    Description: HydraTouch;     flags: iscustom;

[Components]
;Name: MULTI;            Description: MultiStore Module;                         Flags: disablenouninstallwarning restart;       MinVersion: 4.0,4.0;
Name: DCOM95;           Description: DCOM for Windows 95;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0;        Types: hydratouch;
Name: DCOM98;           Description: DCOM for Windows 98;                       Flags: disablenouninstallwarning restart fixed; MinVersion: 4.1,0;                                      Types: hydratouch;
Name: MDAC25;           Description: Microsoft Data Access Components 2.5;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0;      Types: hydratouch;
Name: MDAC27;           Description: Microsoft Data Access Components 2.7;      Flags: disablenouninstallwarning restart fixed; MinVersion: 4.9,5.0;                                    Types: hydratouch;

[Tasks]
Name: "desktopicon";            Description: "Crear Icono en el Escritorio";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked
Name: "quicklaunchicon";        Description: "Crear Icono de Acceso Rápido";    GroupDescription: "Additional icons:";  MinVersion: 4,4;        Flags: unchecked

[Files]
;//////
; APP
;//////
; begin VB system files
; (Note: Scroll to the right to see the full lines!)
;Source: "c:\windows\system32\stdole2.tlb";  DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regtypelib
;Source: "vbfiles\msvbvm60.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\oleaut32.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\olepro32.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: "vbfiles\asycfilt.dll"; DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile
;Source: "vbfiles\comcat.dll";   DestDir: "{sys}"; OnlyBelowVersion: 0,6; Flags: restartreplace uninsneveruninstall sharedfile regserver
; end VB system files
;Source: hydraTouch.exe;         DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: zip.exe;                DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: unzip.exe;              DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: mizip.exe;              DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: vacio.jpg;              DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: backgrounde.jpg;        DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: hydra-background-1024x768.jpg; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: f1.jpg;                 DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: auxiliartouch.exe;      DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: copiontouch.exe;        DestDir: "{app}"; CopyMode: alwaysoverwrite;  
Source: "registratouch\registratouch.bat";   DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: "registratouch\registratouch.exe";   DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: ctrlimpatouch.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
Source: sidebar.ocx;           DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: c:\hydra+2041\hyperlbl.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite;                          Flags: sharedfile regserver
;//////
Source: langtouch\langtouch.mdb;    DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\1.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\2.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\3.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\4.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\5.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\6.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\7.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\8.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\9.ico;       DestDir: "{app}\langtouch";  CopyMode: alwaysoverwrite
Source: langtouch\langtouch.mdb;    DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\1.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\2.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\3.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\4.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\5.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\6.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\7.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\8.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: langtouch\9.ico;       DestDir: "{app}\lang";  CopyMode: alwaysoverwrite
Source: etc\artcon.dat.fia;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: etc\bal.dat.fia;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: etc\*.fet;       DestDir: "{app}\etc";  CopyMode: alwaysoverwrite
Source: images\*.*;     destdir: "{app}\images"; copymode: alwaysoverwrite
Source: hiperusera\*.*;     destdir: "{app}"; copymode: alwaysoverwrite

;//////
Source: C:\inno_appEPELSA\3rdparty\inno.txt;        DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\zip_unzip.txt;   DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
Source: C:\inno_appEPELSA\3rdparty\xcopy.zip;       DestDir: "{app}\3rdparty";      CopyMode: alwaysoverwrite
;//////

;//////
; SYS
;//////
Source: systray.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite;         Flags : sharedfile regserver
source: unrar.dll;                            destdir: "{app}"; CopyMode: alwaysoverwrite;
Source: c:\windows\system32\systray.ocx;     DestDir: "{sys}"; CopyMode: alwaysoverwrite;         Flags : sharedfile regserver
Source: c:\windows\system32\RICHTX32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\COMDLG32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRID32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCHRT20.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMCTL.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCOMM32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSMASK32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSWINSCK.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\TABCTL32.OCX;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
;//////
Source: c:\windows\system32\RCHTXES.DLL;     DestDir: "{app}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RICHED32.DLL;    DestDir: "{app}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appepelsa\system\DAO350.DLL;      DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: C:\hydra+Touchscale\Paquete\Support\DAO360.DLL;      DestDir: "{dao}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\ASYCFILT.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\inno_appEPELSA\system\COMCAT.DLL;      DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\DBGRDES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\DBRPRES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\expsrv.dll;      DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSBIND.DLL;      DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSCH2ES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCMCES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSCOMES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSDBRPTR.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\msderun.dll;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET35.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT35.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER35.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\msjtes40.dll;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJET40.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSJINT40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSJTER40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSMSKES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSPRPES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSRD2X35.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD2X40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSRD3X40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSREPL35.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSREPL40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSSTDFMT.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSSTKPRP.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\MSVBVM60.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
;Source: c:\windows\system32\MSVCRT.DLL;      DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
;Source: c:\windows\system32\MSVCRT40.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
;source: c:\windows\system32\ntdll.dll;       DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\MSXBSE35.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\odbcconf.dll;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEAUT32.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\OLEPRO32.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\SCRRNES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\SCRRUN.DLL;      DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\STDFTES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\TABCTES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB5DB.DLL;       DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6ES.DLL;       DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VB6STKIT.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\VBAJET32.DLL;    DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\WINSKES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile
Source: c:\windows\system32\RDOCURS.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\RDO20ES.DLL;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regserver
Source: c:\windows\system32\STDOLE2.TLB;     DestDir: "{sys}"; CopyMode: alwaysskipifsameorolder; Flags: restartreplace uninsneveruninstall sharedfile regtypelib
;***********************************
Source: "c:\windows\system32\MSVBVM60.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\OLEAUT32.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\OLEPRO32.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\ASYCFILT.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\STDOLE2.TLB";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\COMCAT.DLL";   DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\VB6STKIT.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\VB6ES.DLL";    DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSWINSCK.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\WINSKES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSCOMM32.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSCOMES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSSTKPRP.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSPRPES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSCOMCTL.OCX"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\MSCMCES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSVCRT40.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\RDO20ES.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\RDOCURS.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\MSRDO20.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\VB5DB.DLL";    DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile
Source: "c:\windows\system32\MSREPL35.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSRD2X35.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
Source: "c:\windows\system32\expsrv.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\vbajet32.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\msjint35.dll"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSJTER35.DLL"; DestDir: "{app}\support"; CopyMode: alwaysoverwrite
Source: "c:\windows\system32\MSJET35.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver
;Source: "c:\windows\system32\DAO350.DLL";  DestDir: "{app}\support"; CopyMode: alwaysoverwrite; Flags: sharedfile regserver


; ///
; LIB
; ///
Source: C:\inno_appEPELSA\lib\dcom95.EXE;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,0;   Components: DCOM95;     OnlyBelowVersion: 4.1,0;
Source: C:\inno_appEPELSA\lib\dcom98.exe;         DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.1,0;   Components: DCOM98;
Source: C:\inno_appEPELSA\lib\mdac_typ_25.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.0,4.0; Components: MDAC25;      OnlyBelowVersion: 4.9,5.0;
Source: C:\inno_appEPELSA\lib\mdac_typ_27.exe;    DestDir: {tmp}; CopyMode: alwaysoverwrite; MinVersion: 4.9,5.0; Components: MDAC27;
Source: mysql-connector-odbc-5.1.13-win32.msi;    DestDir: "{app}"; CopyMode: alwaysoverwrite


[Icons]
Name: "{group}\HydraTouch";                                                  Filename: "{app}\hydraTouch.exe"; WorkingDir: {app}
Name: "{userdesktop}\HydraTouch";                                            Filename: "{app}\hydraTouch.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\HydraTouch";   Filename: "{app}\hydraTouch.exe"; WorkingDir: {app};   MinVersion: 4,4;        Tasks: quicklaunchicon

[Dirs]
Name: {app}
Name: "{app}\etc"
Name: "{app}\lang"
Name: "{app}\langtouch"
Name: "{app}\dirtmp"
Name: "{app}\images"
Name: "{app}\exporta"
Name: "{app}\backup"
Name: "{app}\images"
Name: "(app)\3rdparty"
Name: "{app}\asorden"

[Run]
Filename: {tmp}\dcom95.EXE;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM95;     MinVersion: 4.0,0;      OnlyBelowVersion: 4.1,0
Filename: {tmp}\dcom98.exe;             Parameters: /r:n /q:u;                  WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: DCOM98;     MinVersion: 4.1,0
Filename: {tmp}\mdac_typ_25.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC25;     MinVersion: 4.0,4.0;    OnlyBelowVersion: 4.9,5.0
Filename: {tmp}\mdac_typ_27.exe;        Parameters: "/Q /C:""setup /QNT""";     WorkingDir: {tmp};      Flags: skipifdoesntexist;       Components: MDAC27;     MinVersion: 4.9,5.0;
;Filename: {app}\registratouch.exe;      WorkingDir: {app}; Flags: runascurrentuser
;////////
Filename: "{app}\hydratouch.exe";            Description: "Launch Hydra";            Flags: nowait postinstall skipifsilent

;[Code]
;begin
;var
;  MyChk: String;
;  if IsWin64 then
;  begin
;    MyChk:='HKLM64';
;  end;
;  else 
;  begin
;    MyChk:='HKLM32';
;  end;
;end;


