; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=HydraTouch
;\\\\\\\\\\\\\\\\\\\\\\
;AppVerName=HydraTouchLite Upper 1.9.6 Patch (16/06/16)
;OutputDir=output\stdTouchLiteUpper-1.9.6\parche
AppVerName=HydraTouchLite 3.6.4 Patch HiperUsera (13102019)
OutputDir=output\stdTouchLiteHiperUsera364\parche
;//////////////////////
AppPublisher=Grupo Epelsa
AppPublisherURL=http://www.grupoepelsa.com
AppSupportURL=http://www.grupoepelsa.com
AppUpdatesURL=http://www.grupoepelsa.com
DefaultDirName={pf}\HydraTouch
DefaultGroupName=Hydra
AlwaysShowComponentsList=true
;//AdminPrivilegesRequired=true

[Files]
;//////
; APP
;//////
Source: hiperusera\*.exe;      DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: hiperusera\*.txt;      DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: auxiliartouch.exe;     DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: copiontouch.exe;       DestDir: "{app}"; CopyMode: alwaysoverwrite;
Source: ctrlimpatouch.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
Source: sidebar.ocx;           DestDir: "{app}"; CopyMode: alwaysoverwrite; Flags : sharedfile regserver
Source: c:\hydra+2041\hyperlbl.ocx;     DestDir: "{app}"; CopyMode: alwaysoverwrite;                          Flags: sharedfile regserver

